# 运行环境,travis支持31种编程语言运行环境,下面指定运行环境为node_js
language: node_js
# 执行node_js运行环境的版本,通过node -v 可查看本机node版本
node_js:
  - 12
script:
  - npm run docs:build
deploy:
  privoder: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  target_brach: gh-pages
  keep_history: true
  on:
    branch: main

